### ISSUE TITLE
powerGenerate is not correctly displayed if no power is generated

### ISSUE THREAD

**Issue by bakito** [mwittig/pimatic-fronius-solar#11]
If Fronius generates no power (at night) the inverter returns "P_PV": null, but pimatic does not get an update and keeps displaying the last not null value that it got from the inverter.

It would be nice, if the plugin displayed 0 if nothing is generated.

**Comment by mwittig** [comment]
Sorry, for the delay in reply. Your request makes sense to me even though skipping null values is the default   behavior with pimatic.

**Comment by mwittig** [comment]
Released pimatic-fronius-solar@0.0.18
